### ISSUE TITLE
blockAccess is out of date

### ISSUE THREAD

**Issue by LucolesLTDA** [upchuk/d8-demo-modules#1]
hey there, 

I believe your `blockAccess` method implementation is out of date. as a result, the website crashes when your block is enabled. 

here's the relevant change from **/core/modules/block/tests/modules/block_test/src/Plugin/Block/TestBlockInstantiation.php**: 

``` php
  protected function blockAccess(AccountInterface $account) {
    return AccessResult::allowedIfHasPermission($account, 'access content');
  }
```

also don't forget `use Drupal\Core\Access\AccessResult;` on top. that worked for me ;) 

cheers, 
Luciano

**Comment by upchuk** [comment]
@lucoweb Hey there, thanks for the catch. All fixed now!

D
