### ISSUE TITLE
EntityStorage rather than entity.manager

### ISSUE THREAD

**Issue by powpow12** [upchuk/d8-demo-modules#4]
Curious with decision of EntityStorage vs using EntityTypeManager for this line:
```
      $container->get('entity.manager')->getStorage('node')
```

If I wanted to load a user, can I use this with the change `...->getStorage('user')`

**Comment by cyberlex404** [comment]
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityManager.php/class/EntityManager/8.4.x

> Deprecated in Drupal 8.0.0, will be removed before Drupal 9.0.0.

Use https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityTypeManager.php/class/EntityTypeManager/8.4.x
`$container->get('entity_type.manager')->getStorage('node')`
Or
`\Drupal::entityTypeManager->getStorage('node');`

**Comment by powpow12** [comment]
excellent thanks so much!
